SCIPROD-315, Remove content
dnanexus/dnanexus-example-applets pull request #20
Opened 2022-02-08 17:12 UTC by keegankelsey

SCIPROD-315, Remove content

2022-02-08 23:21 UTC, commandlinegirl requested changes
Please remove from Readme a hint that examples (separate from tutorials) are provided here, e.g. "After reading through the tutorials and examples, you should be able ..."

2022-02-09 00:46 UTC, keegankelsey commented
> Please remove from Readme a hint that examples (separate from tutorials) are provided here, e.g. "After reading through the tutorials and examples, you should be able ..."

Updated

2022-02-09 00:51 UTC, commandlinegirl approved these changes
LGTM, thank you!

2022-02-11 18:34 UTC, commandlinegirl approved these changes

2022-02-14 19:47 UTC, merged